name: "Sync Figma Variables from FigMayo"
description: "Fetches figma variables from FigMayo API and creates a PR to update them in your repo."
author: "FigMayo"
branding:
  icon: "zap"
  color: "blue"
inputs:
  gh-pat:
    description: "GitHub personal access token for authenticating gh CLI."
    required: true
  figmayo-api-key:
    description: "FigMayo API Key"
    required: true
  file-path:
    description: "Path to save the figma variables JSON file"
    required: true
outputs:
  pr-url:
    description: "URL of the created pull request"
    value: ${{ steps.create-pr.outputs.pr-url }}
  branch-name:
    description: "Name of the branch created for the PR"
    value: ${{ steps.generate-branch-name.outputs.branch-name }}
  changes:
    description: "Indicates whether changes were detected. If this is false the pr-url and branch-name outputs will be empty."
    value: ${{ steps.git-check.output.changes }}

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        set -e
        if [[ -z "${{ inputs.gh-pat }}" ]]; then
          echo "❌ Error: 'gh-pat' input is required but not provided. Go here to create one https://github.com/settings/personal-access-tokens"
          exit 1
        fi

        if [[ -z "${{ inputs.figmayo-api-key }}" ]]; then
          echo "❌ Error: 'figmayo-api-key' input is required but not provided. Go here to create one https://app.figmayo.com/api/v2/settings"
          exit 1
        fi

        if [[ -z "${{ inputs.file-path }}" ]]; then
          echo "❌ Error: 'file-path' input is required but not provided."
          exit 1
        fi
    - name: Checkout Base Branch
      uses: actions/checkout@v4

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name 'FigMayo Bot'
        git config --global user.email 'support@figmayo.com'

    - name: Generate Unique Branch Name
      shell: bash
      id: generate-branch-name
      run: |
        # Generate a branch name based on the ref and timestamp
        BRANCH_NAME="figmayo/sync-figma-variables/${{ github.ref_name }}-$(date +'%Y%m%d%H%M%S' | tr -d '\n')"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "Generated branch name: $BRANCH_NAME"

        git checkout -b $BRANCH_NAME

    - name: Ensure Target Directory Exists
      shell: bash
      run: |
        dir=$(dirname "${{ inputs.file-path }}")
        mkdir -p "$dir" # Create the directory if it doesn't exist

    - name: Fetch Figma Variables
      shell: bash
      run: |
        curl -H "x-figmayo-key: ${{ inputs.figmayo-api-key }}" https://app.figmayo.com/api/v2/plugin/variables -o ${{ inputs.file-path }}

    - name: Stage File for Git Diff
      shell: bash
      run: |
        git add ${{ inputs.file-path }}

    - name: Check for Changes
      id: git-check
      shell: bash
      run: |
        if git diff --cached --quiet; then
          echo "CHANGES=false" >> $GITHUB_ENV
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "CHANGES=true" >> $GITHUB_ENV
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Debugging Output
      shell: bash
      run: |
        # Debugging Output
        echo "Changes detected: ${{ env.CHANGES }}"

    - name: Commit Changes
      if: env.CHANGES == 'true'
      shell: bash
      run: |
        git add ${{ inputs.file-path }}
        git commit -m "Updated Figma variables from FigMayo API"
        git push origin ${{ env.BRANCH_NAME }}

    - name: Authenticate GitHub CLI
      if: env.CHANGES == 'true'
      shell: bash
      run: echo "${{ inputs.gh-pat }}" | gh auth login --with-token

    # Create Pull Request
    - name: Create Pull Request
      if: env.CHANGES == 'true'
      id: create-pr
      shell: bash
      run: |
        PR_URL=$(gh pr create \
          --base ${{ github.ref_name }} \
          --head  ${{ env.BRANCH_NAME }} \
          --title "Update Figma variables" \
          --body  "This is a FigMayo automated PR raised by the sync-figma-variables action.")
        echo "PR URL: $PR_URL"
        echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        echo "pr-url=$PR_URL" >> $GITHUB_OUTPUT
