name: Test Sync Figma Variables Composite Action

on:
  workflow_dispatch: # Allows manual execution

jobs:
  sync-figma-variables:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.test-sync.outputs.changes }}
      branch-name: ${{ steps.test-sync.outputs.branch-name }}
      pr-url: ${{ steps.test-sync.outputs.pr-url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Sync Figma Variables
        id: test-sync
        uses: ./
        with:
          gh-pat: ${{ secrets.GH_PAT }}
          figmayo-api-key: ${{ secrets.FIGMAYO_API_KEY }}
          file-path: "test/figma-variables.json"

      - name: Debug GITHUB_ENV
        shell: bash
        run: |
          echo "Changes: ${{ steps.test-sync.outputs.changes }}"
          echo "Branch Name: ${{ steps.test-sync.outputs.branch-name || 'No branch created' }}"
          echo "PR URL: ${{ steps.test-sync.outputs.pr-url || 'No PR created' }}"
          echo "Changes: ${{ env.CHANGES }}"
          echo "Branch Name: ${{ env.BRANCH_NAME || 'No branch created' }}"
          echo "PR URL: ${{ env.PR_URL || 'No PR created' }}"
  test-outputs:
    runs-on: ubuntu-latest
    needs: sync-figma-variables
    steps:
      - run: echo '${{ toJSON(needs.sync-figma-variables.outputs) }}'
